name: .NET Core
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies for all projects
      run: dotnet restore
      
    - name: Build all projects
      run: dotnet build --configuration Release --no-restore
    - name: Publish portal project in Release mode
      run: dotnet publish AnimalAdoption.Web.Portal\AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
